outputfile = io.open("image_definitions.lua", "w")

outputfile:write("-- auto-generated by automatic_definition.lua")

function writeDefinitionChunk(character, number, numberL, numberR)
    local letter = "a"
    outputfile:write('\nimage_' .. character .. '["' .. number .. '"] = {"' .. character .. '/' .. numberL .. 'l.png", "' .. character .. '/' .. numberR .. 'r.png", "' .. character .. '/' .. letter .. '.png"}\n')
    repeat
        outputfile:write('image_' .. character .. '["' .. number .. '' .. letter .. '"] = {"' .. character .. '/' .. numberL .. 'l.png", "' .. character .. '/' .. numberR .. 'r.png", "' .. character .. '/' .. letter .. '.png"}\n')
        letter = string.char(string.byte(letter) + 1)
    until string.byte(letter) == 123
end

function writeDefinitionSmall(character, number, numberL, numberR)
    local letter = "a"
    outputfile:write("\nimage_" .. character .. '["' .. number .. '"] = {"' .. character .. '/' .. numberL .. letter .. '.png"}\n')
    repeat
        outputfile:write("image_" .. character .. '["' .. number .. letter .. '"] = {"' .. character .. '/' .. numberL .. letter .. '.png"}\n')
        letter = string.char(string.byte(letter) + 1)
    until string.byte(letter) == 101
end

function writeDefinitionCharacter(character)
    outputfile:write('\nimage_' .. character .. ' = {}\n')
    writeDefinitionChunk(character, "1", "1", "1")
    writeDefinitionChunk(character, "2", "1", "2")
    writeDefinitionChunk(character, "3", "2", "1")
    writeDefinitionChunk(character, "4", "2", "2")

end

writeDefinitionCharacter("sayori")
writeDefinitionCharacter("natsuki")
writeDefinitionCharacter("yuri")
writeDefinitionCharacter("monika")

outputfile:close()